package openvm

import (
	"crypto/sha256"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strconv"

	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/mount"
	"github.com/pelletier/go-toml/v2"

	"github.com/han0110/provoor/pkg/cluster"
)

// Deployment constants. The API and worker ports are fixed so the manager,
// the workers, and the callers agree without configuration. The ready line
// is the message a worker logs once its socket binds, after building every
// loadout program, worded by the pinned image, so an image that rewords it
// updates the constant alongside the tag bump. The final-proofs and metrics
// directories bind the same host path every deployment, so completed proofs
// survive teardown and logged paths resolve identically on the host.
const (
	apiPort               = 3000
	workerPortBase        = 8001
	coordinatorContainer  = "openvm-coordinator"
	workerContainerPrefix = "openvm-worker-"
	keygenContainer       = "openvm-keygen"
	artifactsDir          = "/data/artifacts"
	metricsOutputDir      = "/data/metrics"
	rvrCacheDir           = "/var/cache/openvm-rvr"
	guestELFPath          = "/guests/guest.elf"
	managerConfig         = "/tmp/openvm-manager.toml"
	finalProofsDir        = "/var/tmp/openvm-final-proofs"
	metricsDir            = "/var/tmp/openvm-metrics"
	workerReadyLine       = "Edge Worker listening on"
	// Version every loadout entry carries. The cluster never interprets it,
	// but loadout membership matches on it, so client and deployment fix it
	// at zero.
	programVersion = 0
	// Aggregation shape and watchdog knobs of the manager's proof pipeline,
	// fixed to the values the pinned image is tuned for.
	leafArity         = 4
	internalArity     = 3
	leafPackThreshold = 1000
	// Page size of the workers' virtual pinned-memory GPU allocator.
	vpmmPageSize = 16777216
)

func (cfg *Config) imageRef() string {
	return cfg.Image + ":" + cfg.ImageTag
}

// The artifacts volume keys on the image tag because its keyset is derived
// under that image's VM configuration. The RVR cache volume holds the
// workers' native-compile cache and survives restarts.
func artifactsVolume(tag string) string {
	return "openvm-artifacts-" + tag
}

func rvrCacheVolume(tag string) string {
	return "openvm-rvr-cache-" + tag
}

func workerContainer(gpu int) string {
	return workerContainerPrefix + strconv.Itoa(gpu)
}

func workerConfigPath(gpu int) string {
	return fmt.Sprintf("/tmp/openvm-worker-%d.toml", gpu)
}

// numProvers is the cluster-wide worker container count, which sizes prover
// ids, the manager's registration floor, and each worker's shard index.
func numProvers(cfg *Config) int {
	return len(cfg.Workers)
}

// program is one loadout entry, named by its guest ELF's content digest.
type program struct {
	name   string
	source string
	elf    []byte
}

// programName derives the loadout name of a guest ELF, the first eight bytes
// of its SHA-256 digest in hex. A client reaching a deployment built from a
// different guest is refused by name rather than proving against the wrong
// keyset.
func programName(elf []byte) string {
	digest := sha256.Sum256(elf)
	return "program-" + hex.EncodeToString(digest[:8])
}

// edgePrograms renders the EDGE_PROGRAMS loadout JSON the manager and every
// worker receive.
func edgePrograms(programs []program) string {
	entries := make([]struct {
		Name    string `json:"name"`
		Version int    `json:"version"`
	}, len(programs))
	for i, p := range programs {
		entries[i].Name = p.name
		entries[i].Version = programVersion
	}
	data, _ := json.Marshal(entries)
	return string(data)
}

// workerRustLog quiets the CUDA memory manager at the default level, whose
// per-allocation logging floods the journal.
func workerRustLog(verbose int) string {
	if verbose == 0 {
		return "info,openvm_cuda_common::memory_manager=warn"
	}
	return cluster.RustLog(verbose)
}

// proverLimits is the [provers] table the manager and every worker carry,
// one shared shape because the cluster requires their capacities to agree.
// Only the workers set the segment memory, the manager's table omits it.
type proverLimits struct {
	MaxAppProvers        int   `toml:"max_app_provers"`
	MaxLeafProvers       int   `toml:"max_leaf_provers"`
	MaxInternalProvers   int   `toml:"max_internal_provers"`
	DefaultSegmentMemory int64 `toml:"default_segment_memory,omitempty"`
}

func proverLimitsOf(cfg *Config, segmentMemory int64) proverLimits {
	return proverLimits{
		MaxAppProvers:        cfg.Config.AppProvers,
		MaxLeafProvers:       cfg.Config.LeafProvers,
		MaxInternalProvers:   cfg.Config.InternalProvers,
		DefaultSegmentMemory: segmentMemory,
	}
}

// renderTOML marshals a configuration document under the generated-by
// header. Field order fixes the rendered table order.
func renderTOML(doc any) string {
	data, _ := toml.Marshal(doc)
	return "# Generated by provoor.\n" + string(data)
}

// managerTOML renders the edge-manager configuration.
func managerTOML(cfg *Config) string {
	var doc struct {
		Server struct {
			ListenAddr    string `toml:"listen_addr"`
			NumWorkers    int    `toml:"num_workers"`
			ArtifactsPath string `toml:"artifacts_path"`
		} `toml:"server"`
		Provers proverLimits `toml:"provers"`
		Proof   struct {
			LeafArity             int    `toml:"leaf_arity"`
			InternalArity         int    `toml:"internal_arity"`
			LeafPackThreshold     int    `toml:"leaf_pack_threshold"`
			TimeoutSecs           int    `toml:"timeout_secs"`
			PersistFinalProofsDir string `toml:"persist_final_proofs_dir"`
		} `toml:"proof"`
		Metrics struct {
			OutputDir string `toml:"output_dir"`
		} `toml:"metrics"`
		Telemetry struct {
			LogLevel string `toml:"log_level"`
		} `toml:"telemetry"`
	}
	doc.Server.ListenAddr = fmt.Sprintf("0.0.0.0:%d", apiPort)
	doc.Server.NumWorkers = numProvers(cfg)
	doc.Server.ArtifactsPath = artifactsDir
	doc.Provers = proverLimitsOf(cfg, 0)
	doc.Proof.LeafArity = leafArity
	doc.Proof.InternalArity = internalArity
	doc.Proof.LeafPackThreshold = leafPackThreshold
	doc.Proof.TimeoutSecs = cfg.Config.TimeoutSecs
	doc.Proof.PersistFinalProofsDir = finalProofsDir
	doc.Metrics.OutputDir = metricsOutputDir
	doc.Telemetry.LogLevel = cluster.RustLog(cfg.Verbose)
	return renderTOML(doc)
}

// managerURL is the manager address a worker registers against. A worker
// co-located with the coordinator dials loopback and the rest dial the
// coordinator's data-network address.
func managerURL(cfg *Config, worker Worker) string {
	host := cfg.Coordinator.IP
	if worker.Name == cfg.Coordinator.Name {
		host = "127.0.0.1"
	}
	return fmt.Sprintf("http://%s:%d", host, apiPort)
}

// workerURL is the address a worker advertises for the manager to dial
// back, its own data-network address, or loopback for a co-located worker
// that names none.
func workerURL(worker Worker) string {
	host := worker.IP
	if host == "" {
		host = "127.0.0.1"
	}
	return fmt.Sprintf("http://%s:%d", host, workerPortBase+worker.GPU)
}

// workerTOML renders one worker container's configuration. proverID is the
// worker's position in the configuration, which shards proving work across
// the cluster.
func workerTOML(cfg *Config, worker Worker, proverID int) string {
	var doc struct {
		Server struct {
			ListenAddr string `toml:"listen_addr"`
		} `toml:"server"`
		Worker struct {
			ProverID   int    `toml:"prover_id"`
			NumProvers int    `toml:"num_provers"`
			WorkerURL  string `toml:"worker_url"`
			ManagerURL string `toml:"manager_url"`
		} `toml:"worker"`
		Artifacts struct {
			ArtifactsPath string `toml:"artifacts_path"`
		} `toml:"artifacts"`
		Provers   proverLimits `toml:"provers"`
		Telemetry struct {
			LogLevel string `toml:"log_level"`
		} `toml:"telemetry"`
	}
	doc.Server.ListenAddr = fmt.Sprintf("0.0.0.0:%d", workerPortBase+worker.GPU)
	doc.Worker.ProverID = proverID
	doc.Worker.NumProvers = numProvers(cfg)
	doc.Worker.WorkerURL = workerURL(worker)
	doc.Worker.ManagerURL = managerURL(cfg, worker)
	doc.Artifacts.ArtifactsPath = artifactsDir
	doc.Provers = proverLimitsOf(cfg, cfg.Config.SegmentMemory)
	doc.Telemetry.LogLevel = workerRustLog(cfg.Verbose)
	return renderTOML(doc)
}

// cpusetCPUs is one worker container's even share of its host's CPUs, by
// position among the host's workers, with the last taking the remainder.
func cpusetCPUs(position, hostWorkers, hostCPUs int) string {
	share := hostCPUs / hostWorkers
	last := (position+1)*share - 1
	if position == hostWorkers-1 {
		last = hostCPUs - 1
	}
	return fmt.Sprintf("%d-%d", position*share, last)
}

func coordinatorSpec(cfg *Config, loadout string) (*container.Config, *container.HostConfig) {
	containerCfg := &container.Config{
		Image: cfg.imageRef(),
		Env: []string{
			"RUST_LOG=" + cluster.RustLog(cfg.Verbose),
			"RUST_BACKTRACE=1",
			"NO_COLOR=1",
			"EDGE_PROGRAMS=" + loadout,
		},
		Cmd: []string{"edge-manager", "--config", managerConfig},
	}
	hostCfg := &container.HostConfig{
		NetworkMode:   "host",
		RestartPolicy: container.RestartPolicy{Name: container.RestartPolicyOnFailure},
		LogConfig:     cluster.Journald(coordinatorContainer),
		Mounts: []mount.Mount{
			{
				Type:     mount.TypeVolume,
				Source:   artifactsVolume(cfg.ImageTag),
				Target:   artifactsDir,
				ReadOnly: true,
			},
			{
				Type:        mount.TypeBind,
				Source:      finalProofsDir,
				Target:      finalProofsDir,
				BindOptions: &mount.BindOptions{CreateMountpoint: true},
			},
			{
				Type:        mount.TypeBind,
				Source:      metricsDir,
				Target:      metricsOutputDir,
				BindOptions: &mount.BindOptions{CreateMountpoint: true},
			},
		},
	}
	return containerCfg, hostCfg
}

func workerSpec(cfg *Config, gpu int, cpuset, loadout string) (*container.Config, *container.HostConfig) {
	containerCfg := &container.Config{
		Image: cfg.imageRef(),
		Env: []string{
			"RUST_LOG=" + workerRustLog(cfg.Verbose),
			"RUST_BACKTRACE=1",
			"NO_COLOR=1",
			"VPMM_PAGE_SIZE=" + strconv.Itoa(vpmmPageSize),
			"VPMM_PAGES=0",
			"EDGE_PROGRAMS=" + loadout,
			"OPENVM_RVR_NATIVE_CACHE_DIR=" + rvrCacheDir,
		},
		Cmd: []string{"edge-worker", "--config", workerConfigPath(gpu)},
	}
	hostCfg := &container.HostConfig{
		NetworkMode:   "host",
		RestartPolicy: container.RestartPolicy{Name: container.RestartPolicyOnFailure},
		ShmSize:       int64(cfg.Config.ShmSizeGB) << 30,
		CapAdd:        []string{"SYS_NICE"},
		LogConfig:     cluster.Journald(workerContainer(gpu)),
		Mounts: []mount.Mount{
			{
				Type:     mount.TypeVolume,
				Source:   artifactsVolume(cfg.ImageTag),
				Target:   artifactsDir,
				ReadOnly: true,
			},
			{
				Type:   mount.TypeVolume,
				Source: rvrCacheVolume(cfg.ImageTag),
				Target: rvrCacheDir,
			},
		},
		Resources: container.Resources{
			CpusetCpus: cpuset,
			Ulimits:    []*container.Ulimit{{Name: "memlock", Soft: -1, Hard: -1}},
			DeviceRequests: []container.DeviceRequest{{
				DeviceIDs:    []string{strconv.Itoa(gpu)},
				Capabilities: [][]string{{"gpu"}},
			}},
		},
	}
	return containerCfg, hostCfg
}

// keygenScript is embedded from its sidecar file so it stays editable and
// lintable as shell, with its parameters supplied as container environment.
// Embedded scripts sit next to the Go file that embeds them, one file per
// script, named after the embedding variable.
//
//go:embed keygen.sh
var keygenScript string

func keygenSpec(cfg *Config, prog program) (*container.Config, *container.HostConfig) {
	containerCfg := &container.Config{
		Image: cfg.imageRef(),
		Env: []string{
			"ARTIFACTS_DIR=" + artifactsDir,
			"PROGRAM_NAME=" + prog.name,
			"PROGRAM_VERSION=" + strconv.Itoa(programVersion),
			"GUEST_ELF=" + guestELFPath,
		},
		Cmd: []string{"bash", "-c", keygenScript},
	}
	hostCfg := &container.HostConfig{
		ShmSize: int64(cfg.Config.ShmSizeGB) << 30,
		Mounts: []mount.Mount{{
			Type:   mount.TypeVolume,
			Source: artifactsVolume(cfg.ImageTag),
			Target: artifactsDir,
		}},
		Resources: container.Resources{
			Ulimits: []*container.Ulimit{{Name: "memlock", Soft: -1, Hard: -1}},
			DeviceRequests: []container.DeviceRequest{
				{Count: -1, Capabilities: [][]string{{"gpu"}}},
			},
		},
	}
	return containerCfg, hostCfg
}
