package openvm

import (
	"reflect"
	"strings"
	"testing"

	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/mount"

	"github.com/han0110/provoor/pkg/cluster"
)

func testConfig() *Config {
	return &Config{
		Zkvm:        "openvm",
		ZkvmVersion: "2.1.0-preview",
		Image:       "ghcr.io/han0110/provoor/openvm",
		ImageTag:    "2.1.0-preview",
		Guests:      []cluster.Guest{{ELF: "/guests/a.elf", VK: "/guests/a.vk"}},
		Coordinator: cluster.Node{
			SSH: "user@203.0.113.1",
			IP:  "10.0.0.1",
		},
		Workers: []Worker{
			{Node: cluster.Node{SSH: "user@203.0.113.1"}, GPU: 0},
			{Node: cluster.Node{SSH: "user@203.0.113.1"}, GPU: 1},
			{Node: cluster.Node{SSH: "user@203.0.113.2", IP: "10.0.0.2"}, GPU: 0},
			{Node: cluster.Node{SSH: "user@203.0.113.2", IP: "10.0.0.2"}, GPU: 1},
		},
		Config: ProverConfig{
			AppProvers:      2,
			LeafProvers:     2,
			InternalProvers: 1,
			TimeoutSecs:     1800,
			ShmSizeGB:       2,
		},
	}
}

func TestProgramName(t *testing.T) {
	if got := programName([]byte("test")); got != "program-9f86d081884c7d65" {
		t.Errorf("programName = %q", got)
	}
}

func TestEdgePrograms(t *testing.T) {
	programs := []program{
		{name: "program-9f86d081884c7d65"},
		{name: "program-0123456789abcdef"},
	}
	want := `[{"name":"program-9f86d081884c7d65","version":0},{"name":"program-0123456789abcdef","version":0}]`
	if got := edgePrograms(programs); got != want {
		t.Errorf("edgePrograms = %s", got)
	}
}

// TestManagerTOMLOmitsUnsetTimeout pins the mechanism the whole configuration
// rests on. An unset knob has to leave the rendered file entirely, since the
// manager reads a zero as a zero and rejects it, and only an absent key falls
// through to the deadline the image itself carries.
func TestManagerTOMLOmitsUnsetTimeout(t *testing.T) {
	cfg := testConfig()
	cfg.Config.TimeoutSecs = 0
	if strings.Contains(managerTOML(cfg), "timeout_secs") {
		t.Errorf("an unset timeout must not be rendered, got\n%s", managerTOML(cfg))
	}
}

func TestManagerTOML(t *testing.T) {
	want := `# Generated by provoor.
[server]
listen_addr = '0.0.0.0:3000'
num_workers = 4
artifacts_path = '/data/artifacts'

[provers]
max_app_provers = 2
max_leaf_provers = 2
max_internal_provers = 1

[proof]
leaf_arity = 4
internal_arity = 3
leaf_pack_threshold = 1000
timeout_secs = 1800
persist_final_proofs_dir = '/var/tmp/openvm-final-proofs'

[metrics]
output_dir = '/data/metrics'

[telemetry]
log_level = 'info'
`
	if got := managerTOML(testConfig()); got != want {
		t.Errorf("toml =\n%s\nwant\n%s", got, want)
	}
}

func TestWorkerTOML(t *testing.T) {
	cfg := testConfig()
	want := `# Generated by provoor.
[server]
listen_addr = '0.0.0.0:8002'

[worker]
prover_id = 3
num_provers = 4
worker_url = 'http://10.0.0.2:8002'
manager_url = 'http://10.0.0.1:3000'

[artifacts]
artifacts_path = '/data/artifacts'

[provers]
max_app_provers = 2
max_leaf_provers = 2
max_internal_provers = 1

[telemetry]
log_level = 'info,openvm_cuda_common::memory_manager=warn'
`
	if got := workerTOML(cfg, cfg.Workers[3], 3); got != want {
		t.Errorf("toml =\n%s\nwant\n%s", got, want)
	}
}

func TestWorkerTOMLColocatedDialsLoopback(t *testing.T) {
	cfg := testConfig()
	toml := workerTOML(cfg, cfg.Workers[0], 0)
	for _, required := range []string{
		`worker_url = 'http://127.0.0.1:8001'`,
		`manager_url = 'http://127.0.0.1:3000'`,
		"prover_id = 0",
	} {
		if !strings.Contains(toml, required) {
			t.Errorf("toml lacks %q:\n%s", required, toml)
		}
	}
}

func TestWorkerTOMLSegmentMemory(t *testing.T) {
	cfg := testConfig()
	cfg.Config.SegmentMemory = 15569256448
	toml := workerTOML(cfg, cfg.Workers[0], 0)
	if !strings.Contains(toml, "max_internal_provers = 1\ndefault_segment_memory = 15569256448\n\n[telemetry]") {
		t.Errorf("segment memory misplaced:\n%s", toml)
	}
}

func TestCpusetCPUs(t *testing.T) {
	for _, tt := range []struct {
		position, hostWorkers, hostCPUs int
		want                            string
	}{
		{0, 2, 32, "0-15"},
		{1, 2, 32, "16-31"},
		{1, 2, 31, "15-30"},
		{0, 1, 8, "0-7"},
	} {
		if got := cpusetCPUs(tt.position, tt.hostWorkers, tt.hostCPUs); got != tt.want {
			t.Errorf("cpusetCPUs(%d, %d, %d) = %q, want %q", tt.position, tt.hostWorkers, tt.hostCPUs, got, tt.want)
		}
	}
}

func TestCoordinatorSpec(t *testing.T) {
	containerCfg, hostCfg := coordinatorSpec(testConfig(), `[{"name":"program-x","version":0}]`)
	if containerCfg.Image != "ghcr.io/han0110/provoor/openvm:2.1.0-preview" {
		t.Errorf("Image = %q", containerCfg.Image)
	}
	wantCmd := []string{"edge-manager", "--config", "/tmp/openvm-manager.toml"}
	if !reflect.DeepEqual([]string(containerCfg.Cmd), wantCmd) {
		t.Errorf("Cmd = %v", containerCfg.Cmd)
	}
	wantEnv := []string{
		"RUST_LOG=info",
		"RUST_BACKTRACE=1",
		"NO_COLOR=1",
		`EDGE_PROGRAMS=[{"name":"program-x","version":0}]`,
	}
	if !reflect.DeepEqual(containerCfg.Env, wantEnv) {
		t.Errorf("Env = %v", containerCfg.Env)
	}
	if hostCfg.NetworkMode != "host" {
		t.Errorf("NetworkMode = %v", hostCfg.NetworkMode)
	}
	if hostCfg.RestartPolicy.Name != container.RestartPolicyOnFailure {
		t.Errorf("RestartPolicy = %v", hostCfg.RestartPolicy)
	}
	if hostCfg.LogConfig.Type != "journald" || hostCfg.LogConfig.Config["tag"] != "openvm-coordinator" {
		t.Errorf("LogConfig = %+v", hostCfg.LogConfig)
	}
	if len(hostCfg.Mounts) != 3 ||
		hostCfg.Mounts[0].Source != "openvm-artifacts-2.1.0-preview" ||
		hostCfg.Mounts[0].Target != "/data/artifacts" ||
		!hostCfg.Mounts[0].ReadOnly {
		t.Errorf("Mounts = %+v", hostCfg.Mounts)
	}
	for i, want := range []mount.Mount{
		{},
		{Source: "/var/tmp/openvm-final-proofs", Target: "/var/tmp/openvm-final-proofs"},
		{Source: "/var/tmp/openvm-metrics", Target: "/data/metrics"},
	} {
		if i == 0 {
			continue
		}
		got := hostCfg.Mounts[i]
		if got.Type != mount.TypeBind || got.Source != want.Source || got.Target != want.Target ||
			got.BindOptions == nil || !got.BindOptions.CreateMountpoint {
			t.Errorf("Mounts[%d] = %+v", i, got)
		}
	}
}

func TestWorkerSpec(t *testing.T) {
	cfg := testConfig()
	containerCfg, hostCfg := workerSpec(cfg, 1, "16-31", `[]`)
	wantCmd := []string{"edge-worker", "--config", "/tmp/openvm-worker-1.toml"}
	if !reflect.DeepEqual([]string(containerCfg.Cmd), wantCmd) {
		t.Errorf("Cmd = %v", containerCfg.Cmd)
	}
	wantEnv := []string{
		"RUST_LOG=info,openvm_cuda_common::memory_manager=warn",
		"RUST_BACKTRACE=1",
		"NO_COLOR=1",
		"VPMM_PAGE_SIZE=16777216",
		"VPMM_PAGES=0",
		"EDGE_PROGRAMS=[]",
		"OPENVM_RVR_NATIVE_CACHE_DIR=/var/cache/openvm-rvr",
	}
	if !reflect.DeepEqual(containerCfg.Env, wantEnv) {
		t.Errorf("Env = %v", containerCfg.Env)
	}
	if hostCfg.NetworkMode != "host" || hostCfg.ShmSize != 2<<30 {
		t.Errorf("NetworkMode = %v, ShmSize = %d", hostCfg.NetworkMode, hostCfg.ShmSize)
	}
	if !reflect.DeepEqual([]string(hostCfg.CapAdd), []string{"SYS_NICE"}) {
		t.Errorf("CapAdd = %v", hostCfg.CapAdd)
	}
	if hostCfg.LogConfig.Config["tag"] != "openvm-worker-1" {
		t.Errorf("LogConfig = %+v", hostCfg.LogConfig)
	}
	if len(hostCfg.Mounts) != 2 ||
		hostCfg.Mounts[0].Source != "openvm-artifacts-2.1.0-preview" || !hostCfg.Mounts[0].ReadOnly ||
		hostCfg.Mounts[1].Source != "openvm-rvr-cache-2.1.0-preview" ||
		hostCfg.Mounts[1].Target != "/var/cache/openvm-rvr" || hostCfg.Mounts[1].ReadOnly {
		t.Errorf("Mounts = %+v", hostCfg.Mounts)
	}
	if hostCfg.Resources.CpusetCpus != "16-31" {
		t.Errorf("CpusetCpus = %q", hostCfg.Resources.CpusetCpus)
	}
	if len(hostCfg.DeviceRequests) != 1 || !reflect.DeepEqual(hostCfg.DeviceRequests[0].DeviceIDs, []string{"1"}) {
		t.Errorf("DeviceRequests = %+v", hostCfg.DeviceRequests)
	}
	if len(hostCfg.Ulimits) != 1 || hostCfg.Ulimits[0].Name != "memlock" ||
		hostCfg.Ulimits[0].Soft != -1 || hostCfg.Ulimits[0].Hard != -1 {
		t.Errorf("Ulimits = %+v", hostCfg.Ulimits)
	}
}

func TestKeygenSpec(t *testing.T) {
	containerCfg, hostCfg := keygenSpec(testConfig(), program{name: "program-9f86d081884c7d65"})
	if !reflect.DeepEqual([]string(containerCfg.Cmd), []string{"bash", "-c", keygenScript}) {
		t.Errorf("Cmd = %v", containerCfg.Cmd)
	}
	wantEnv := []string{
		"ARTIFACTS_DIR=/data/artifacts",
		"PROGRAM_NAME=program-9f86d081884c7d65",
		"PROGRAM_VERSION=0",
		"GUEST_ELF=/guests/guest.elf",
	}
	if !reflect.DeepEqual(containerCfg.Env, wantEnv) {
		t.Errorf("Env = %v", containerCfg.Env)
	}
	for _, required := range []string{"set -euo pipefail", "${GUEST_ELF}", "${PROGRAM_NAME}", "convert_fixtures keygen", "baseline.bin", "app_pk agg_stark_pk"} {
		if !strings.Contains(keygenScript, required) {
			t.Errorf("keygen script lacks %q", required)
		}
	}
	if hostCfg.ShmSize != 2<<30 {
		t.Errorf("ShmSize = %d", hostCfg.ShmSize)
	}
	if len(hostCfg.Mounts) != 1 || hostCfg.Mounts[0].Source != "openvm-artifacts-2.1.0-preview" ||
		hostCfg.Mounts[0].Target != "/data/artifacts" || hostCfg.Mounts[0].ReadOnly {
		t.Errorf("Mounts = %+v", hostCfg.Mounts)
	}
	if len(hostCfg.DeviceRequests) != 1 || hostCfg.DeviceRequests[0].Count != -1 {
		t.Errorf("DeviceRequests = %+v", hostCfg.DeviceRequests)
	}
}

func TestWorkerRustLog(t *testing.T) {
	if got := workerRustLog(0); got != "info,openvm_cuda_common::memory_manager=warn" {
		t.Errorf("workerRustLog(0) = %q", got)
	}
	if got := workerRustLog(2); got != "trace" {
		t.Errorf("workerRustLog(2) = %q", got)
	}
}
