package zisk

import (
	_ "embed"
	"fmt"
	"strconv"
	"strings"

	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/mount"
	"github.com/docker/go-connections/nat"
)

// Deployment constants. The API and cluster ports are fixed so the
// coordinator, the workers, and the callers agree without configuration. The
// registration line is the message the worker logs once the coordinator
// accepts it, worded by the pinned image, so an image that rewords it updates
// the constant alongside the tag bump.
const (
	apiPort              = 7000
	clusterPort          = 50051
	coordinatorContainer = "zisk-coordinator"
	workerContainer      = "zisk-worker"
	setupContainer       = "zisk-proving-key-setup"
	provingKeyDir        = "/root/.zisk/provingKey"
	setupKeyBaseURL      = "https://storage.googleapis.com/zisk-setup"
	coordinatorConfig    = "/tmp/zisk-coordinator.toml"
	registrationLine     = "Registration accepted: Registration successful"
	// Compute units each worker advertises to the coordinator, fixed by the
	// worker image. The coordinator config derives its readiness floor from
	// this and the worker count.
	computeUnitsPerWorker = 10
)

func (cfg *Config) imageRef() string {
	return cfg.Image + ":" + cfg.ImageTag
}

func provingKeyVolume(tag string) string {
	return "zisk-proving-key-" + tag
}

func rustLog(verbose int) string {
	switch verbose {
	case 0:
		return "info"
	case 1:
		return "debug"
	default:
		return "trace"
	}
}

func journald(containerName string) container.LogConfig {
	return container.LogConfig{
		Type:   "journald",
		Config: map[string]string{"tag": containerName},
	}
}

// coordinatorTOML renders the coordinator config holding a job until the
// full cluster is Ready.
func coordinatorTOML(workerCount int) string {
	return fmt.Sprintf(`# Generated by provoor. Holds a job until the full cluster is Ready.
[backend]
mode = "coordinator"

[coordinator]
# Self-reference so the embedded engine re-reads this file and applies the floor.
config_file = %q
# %d compute units per worker over %d workers.
min_compute_units = %d
`, coordinatorConfig, computeUnitsPerWorker, workerCount, computeUnitsPerWorker*workerCount)
}

func coordinatorSpec(cfg *Config) (*container.Config, *container.HostConfig) {
	api := nat.Port(fmt.Sprintf("%d/tcp", apiPort))
	clusterAPI := nat.Port(fmt.Sprintf("%d/tcp", clusterPort))

	containerCfg := &container.Config{
		Image: cfg.imageRef(),
		Env:   []string{"RUST_LOG=" + rustLog(cfg.Verbose)},
		Cmd: []string{
			"zisk-coordinator",
			"--api-port", strconv.Itoa(apiPort),
			"--cluster-port", strconv.Itoa(clusterPort),
			"--config", coordinatorConfig,
		},
		ExposedPorts: nat.PortSet{api: {}, clusterAPI: {}},
	}
	hostCfg := &container.HostConfig{
		RestartPolicy: container.RestartPolicy{Name: container.RestartPolicyOnFailure},
		PortBindings: nat.PortMap{
			api:        {{HostPort: strconv.Itoa(apiPort)}},
			clusterAPI: {{HostPort: strconv.Itoa(clusterPort)}},
		},
		LogConfig: journald(coordinatorContainer),
	}
	return containerCfg, hostCfg
}

// workerCoordinatorURL is the cluster URL a worker registers against. The
// worker co-located with the coordinator dials loopback and the rest dial the
// data-network cluster address.
func workerCoordinatorURL(cfg *Config, worker Worker) string {
	host := cfg.Coordinator.IP
	if worker.Name == cfg.Coordinator.Name {
		host = "127.0.0.1"
	}
	return fmt.Sprintf("http://%s:%d", host, clusterPort)
}

// workerArgs builds the mpirun invocation, one process spanning the host's
// GPUs with NUMA-aware rank mapping. numaNodes is the worker host's observed
// topology, used only when the configuration leaves mpi_numa_ppr unset.
func workerArgs(cfg *Config, worker Worker, numaNodes int) []string {
	np := cfg.Config.MPINp
	// One rank per NUMA node by default.
	ppr := cfg.Config.MPINumaPpr
	if ppr == 0 {
		ppr = max(np/max(numaNodes, 1), 1)
	}

	args := []string{
		"--report-bindings",
		"--allow-run-as-root",
		"-np", strconv.Itoa(np),
		"-map-by", fmt.Sprintf("ppr:%d:numa", ppr),
		"--bind-to", "numa",
		"--rank-by", "slot",
	}
	// Unset leaves proofman's own choice, physical cores divided by the
	// node's rank count.
	if cfg.Config.MPIThreads > 0 {
		args = append(args, "-x", "RAYON_NUM_THREADS="+strconv.Itoa(cfg.Config.MPIThreads))
	}
	args = append(args,
		"-x", "RUST_LOG="+rustLog(cfg.Verbose),
		"-x", "NO_COLOR=1",
		"-x", "ZISK_HOME=/root/.zisk",
		// Witness generation walks PIL expression trees too deep for the
		// 2 MiB Rust spawned-thread default. 64 MiB matches proofman-cli's
		// stack_size.
		"-x", "RUST_MIN_STACK=67108864",
		"zisk-worker-gpu",
		"--coordinator-url", workerCoordinatorURL(cfg, worker),
		"--worker-id", worker.Name,
		"--gpu",
		// Plans the memory ops on the CPU, working around the GPU planner.
		// The flag exists in the forked image this deployment pins, not in
		// upstream ZisK.
		"--cpu-mops",
		"--proving-key", provingKeyDir,
	)
	if cfg.Config.MaxStreams > 0 {
		args = append(args, "--max-streams", strconv.Itoa(cfg.Config.MaxStreams))
	}
	if cfg.Config.NumberThreadsWitness > 0 {
		args = append(args, "--number-threads-witness", strconv.Itoa(cfg.Config.NumberThreadsWitness))
	}
	if cfg.Config.MaxWitnessStored > 0 {
		args = append(args, "--max-witness-stored", strconv.Itoa(cfg.Config.MaxWitnessStored))
	}
	if cfg.Config.MinimalMemory {
		args = append(args, "--minimal-memory")
	}
	if cfg.Verbose >= 1 {
		args = append(args, "-"+strings.Repeat("v", cfg.Verbose))
	}
	return args
}

func workerSpec(cfg *Config, worker Worker, numaNodes int) (*container.Config, *container.HostConfig, error) {
	gpus, err := parseGpus(worker.Gpus)
	if err != nil {
		return nil, nil, err
	}

	containerCfg := &container.Config{
		Image:      cfg.imageRef(),
		Entrypoint: []string{"mpirun"},
		Cmd:        workerArgs(cfg, worker, numaNodes),
	}
	hostCfg := &container.HostConfig{
		NetworkMode:   "host",
		RestartPolicy: container.RestartPolicy{Name: container.RestartPolicyOnFailure},
		ShmSize:       int64(cfg.Config.ShmSizeGB) << 30,
		LogConfig:     journald(workerContainer),
		// Mounted writable because proofman regenerates a .consttree into
		// the setup path whenever one is missing or older than the .const
		// it derives from, which happens on the first prove after a setup.
		Mounts: []mount.Mount{{
			Type:   mount.TypeVolume,
			Source: provingKeyVolume(cfg.ImageTag),
			Target: provingKeyDir,
		}},
		Resources: container.Resources{
			Ulimits:        []*container.Ulimit{{Name: "memlock", Soft: -1, Hard: -1}},
			DeviceRequests: []container.DeviceRequest{gpus},
		},
	}
	return containerCfg, hostCfg, nil
}

// setupScript is embedded from its sidecar file so it stays editable and
// lintable as shell, with its parameters supplied as container environment.
// Embedded scripts sit next to the Go file that embeds them, one file per
// script, named after the embedding variable.
//
//go:embed setup.sh
var setupScript string

func setupSpec(cfg *Config) (*container.Config, *container.HostConfig) {
	containerCfg := &container.Config{
		Image: cfg.imageRef(),
		Env: []string{
			fmt.Sprintf("KEY_URL=%s/zisk-provingkey-%s.tar.gz", setupKeyBaseURL, cfg.ImageTag),
			"PROVING_KEY_DIR=" + provingKeyDir,
		},
		Cmd: []string{"bash", "-c", setupScript},
	}
	hostCfg := &container.HostConfig{
		ShmSize: 16 << 30,
		Mounts: []mount.Mount{{
			Type:   mount.TypeVolume,
			Source: provingKeyVolume(cfg.ImageTag),
			Target: provingKeyDir,
		}},
		Resources: container.Resources{
			Ulimits: []*container.Ulimit{{Name: "memlock", Soft: -1, Hard: -1}},
			DeviceRequests: []container.DeviceRequest{
				{Count: -1, Capabilities: [][]string{{"gpu"}}},
			},
		},
	}
	return containerCfg, hostCfg
}

// parseGpus turns a docker --gpus value, all, a count, or device=0,1, into a
// device request.
func parseGpus(spec string) (container.DeviceRequest, error) {
	request := container.DeviceRequest{Capabilities: [][]string{{"gpu"}}}
	switch {
	case spec == "all":
		request.Count = -1
	case strings.HasPrefix(spec, "device="):
		request.DeviceIDs = strings.Split(strings.TrimPrefix(spec, "device="), ",")
	default:
		count, err := strconv.Atoi(spec)
		if err != nil || count < 1 {
			return request, fmt.Errorf("gpus expects all, a count, or device=0,1, got %q", spec)
		}
		request.Count = count
	}
	return request, nil
}
