package zisk

import (
	_ "embed"
	"fmt"
	"strconv"
	"strings"

	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/mount"
	"github.com/docker/go-connections/nat"

	"github.com/han0110/provoor/pkg/cluster"
)

// Deployment constants. The API and cluster ports are fixed so the
// coordinator, the workers, and the callers agree without configuration. The
// registration line is the message the worker logs once the coordinator
// accepts it, worded by the pinned image, so an image that rewords it updates
// the constant alongside the tag bump.
const (
	apiPort              = 7000
	clusterPort          = 50051
	coordinatorContainer = "zisk-coordinator"
	workerContainer      = "zisk-worker"
	setupContainer       = "zisk-proving-key-setup"
	provingKeyDir        = "/root/.zisk/provingKey"
	cacheDir             = "/root/.zisk/cache"
	setupKeyBaseURL      = "https://storage.googleapis.com/zisk-setup"
	coordinatorConfig    = "/tmp/zisk-coordinator.toml"
	registrationLine     = "Registration accepted: Registration successful"
	// Compute units one GPU is worth to the coordinator, the unit the worker
	// image advertises per GPU. A worker is told to advertise this times the
	// GPUs it was given and the coordinator derives its readiness floor the
	// same way, so the floor tracks the GPUs actually deployed rather than
	// whatever the image happens to default to.
	computeUnitsPerGPU = 10
)

func (cfg *Config) imageRef() string {
	return cfg.Image + ":" + cfg.ImageTag
}

func provingKeyVolume(zkvmVersion string) string {
	return "zisk-proving-key-" + zkvmVersion
}

func cacheVolume(zkvmVersion string) string {
	return "zisk-cache-" + zkvmVersion
}

// cacheMount is the guest artifact cache the coordinator and the workers
// write, holding the registered ELFs, the rom setup output, and the AOT
// assembly. Everything in it is addressed by ELF hash, so one volume serves
// every guest and survives a down and up, sparing the next setup the work.
func cacheMount(zkvmVersion string) mount.Mount {
	return mount.Mount{
		Type:   mount.TypeVolume,
		Source: cacheVolume(zkvmVersion),
		Target: cacheDir,
	}
}

// coordinatorTOML renders the coordinator config holding a job until every
// GPU of the deployment is Ready.
func coordinatorTOML(workers []Worker) string {
	gpus := 0
	for _, worker := range workers {
		gpus += worker.GPU.Len()
	}
	return fmt.Sprintf(`# Generated by provoor. Holds a job until the full cluster is Ready.
[backend]
mode = "coordinator"

[coordinator]
# Self-reference so the embedded engine re-reads this file and applies the floor.
config_file = %q
# %d compute units per gpu over %d gpus.
min_compute_units = %d
`, coordinatorConfig, computeUnitsPerGPU, gpus, computeUnitsPerGPU*gpus)
}

func coordinatorSpec(cfg *Config) (*container.Config, *container.HostConfig) {
	api := nat.Port(fmt.Sprintf("%d/tcp", apiPort))
	clusterAPI := nat.Port(fmt.Sprintf("%d/tcp", clusterPort))

	containerCfg := &container.Config{
		Image: cfg.imageRef(),
		Env:   []string{"RUST_LOG=" + cluster.RustLog(cfg.Verbose)},
		Cmd: []string{
			"zisk-coordinator",
			"--api-port", strconv.Itoa(apiPort),
			"--cluster-port", strconv.Itoa(clusterPort),
			"--config", coordinatorConfig,
		},
		ExposedPorts: nat.PortSet{api: {}, clusterAPI: {}},
	}
	hostCfg := &container.HostConfig{
		RestartPolicy: container.RestartPolicy{Name: container.RestartPolicyOnFailure},
		PortBindings: nat.PortMap{
			api:        {{HostPort: strconv.Itoa(apiPort)}},
			clusterAPI: {{HostPort: strconv.Itoa(clusterPort)}},
		},
		LogConfig: cluster.Journald(coordinatorContainer),
		Mounts:    []mount.Mount{cacheMount(cfg.ZkvmVersion)},
	}
	return containerCfg, hostCfg
}

// workerCoordinatorURL is the cluster URL a worker registers against. The
// worker co-located with the coordinator dials loopback and the rest dial the
// data-network cluster address.
func workerCoordinatorURL(cfg *Config, worker Worker) string {
	host := cfg.Coordinator.IP
	if worker.SSH == cfg.Coordinator.SSH {
		host = "127.0.0.1"
	}
	return fmt.Sprintf("http://%s:%d", host, clusterPort)
}

// coordinatorEndpoint is the client API URL as the coordinator host sees it,
// which is loopback wherever the coordinator runs. A deployment on this
// machine dials it directly and a remote one reaches the same address through
// the coordinator's SSH destination, so the API never has to be routable from
// wherever provoor runs.
func coordinatorEndpoint() string {
	return fmt.Sprintf("http://127.0.0.1:%d", apiPort)
}

// workerArgs builds the mpirun invocation, one process spanning the host's
// GPUs with NUMA-aware rank mapping. name is the id the worker registers
// under, and numaNodes is the worker host's observed topology, used only when
// the configuration leaves mpi_numa_ppr unset.
func workerArgs(cfg *Config, worker Worker, name string, numaNodes int) []string {
	np := cfg.Config.MPINp
	// One rank per NUMA node by default.
	ppr := cfg.Config.MPINumaPpr
	if ppr == 0 {
		ppr = max(np/max(numaNodes, 1), 1)
	}

	args := []string{
		"--report-bindings",
		"--allow-run-as-root",
		"-np", strconv.Itoa(np),
		"-map-by", fmt.Sprintf("ppr:%d:numa", ppr),
		"--bind-to", "numa",
		"--rank-by", "slot",
	}
	// Unset leaves proofman's own choice, physical cores divided by the
	// node's rank count.
	if cfg.Config.MPIThreads > 0 {
		args = append(args, "-x", "RAYON_NUM_THREADS="+strconv.Itoa(cfg.Config.MPIThreads))
	}
	args = append(args,
		"-x", "RUST_LOG="+cluster.RustLog(cfg.Verbose),
		"-x", "NO_COLOR=1",
		"-x", "ZISK_HOME=/root/.zisk",
		// Witness generation walks PIL expression trees too deep for the
		// 2 MiB Rust spawned-thread default. 64 MiB matches proofman-cli's
		// stack_size.
		"-x", "RUST_MIN_STACK=67108864",
		"zisk-worker-gpu",
		"--coordinator-url", workerCoordinatorURL(cfg, worker),
		"--worker-id", name,
		"--compute-capacity", strconv.Itoa(computeUnitsPerGPU*worker.GPU.Len()),
		"--gpu",
	)
	// The GPU memory-ops planner is linked into the worker and borrows
	// proofman's device buffer, so exhausting its capacity aborts the process
	// rather than failing the job, and one rank aborting takes every rank on
	// the node with it. That capacity is 16384 chunks of 2^18 steps, which is
	// 1024 Main segments, within reach of the blocks this deployment proves.
	// The CPU planner has no such cap, so it stays the default despite being
	// the slower and more memory-hungry of the two.
	if cfg.Config.CPUMops {
		args = append(args, "--cpu-mops")
	}
	args = append(args, "--proving-key", provingKeyDir)
	if cfg.Config.MaxStreams > 0 {
		args = append(args, "--max-streams", strconv.Itoa(cfg.Config.MaxStreams))
	}
	if cfg.Config.NumberThreadsWitness > 0 {
		args = append(args, "--number-threads-witness", strconv.Itoa(cfg.Config.NumberThreadsWitness))
	}
	if cfg.Config.MaxWitnessStored > 0 {
		args = append(args, "--max-witness-stored", strconv.Itoa(cfg.Config.MaxWitnessStored))
	}
	if cfg.Config.MinimalMemory {
		args = append(args, "--minimal-memory")
	}
	if cfg.Verbose >= 1 {
		args = append(args, "-"+strings.Repeat("v", cfg.Verbose))
	}
	return args
}

func workerSpec(cfg *Config, worker Worker, name string, numaNodes int) (*container.Config, *container.HostConfig) {
	containerCfg := &container.Config{
		Image:      cfg.imageRef(),
		Entrypoint: []string{"mpirun"},
		Cmd:        workerArgs(cfg, worker, name, numaNodes),
	}
	hostCfg := &container.HostConfig{
		NetworkMode:   "host",
		RestartPolicy: container.RestartPolicy{Name: container.RestartPolicyOnFailure},
		ShmSize:       int64(cfg.Config.ShmSizeGB) << 30,
		LogConfig:     cluster.Journald(workerContainer),
		// Mounted writable because proofman regenerates a .consttree into
		// the setup path whenever one is missing or older than the .const
		// it derives from, which happens on the first prove after a setup.
		Mounts: []mount.Mount{{
			Type:   mount.TypeVolume,
			Source: provingKeyVolume(cfg.ZkvmVersion),
			Target: provingKeyDir,
		}, cacheMount(cfg.ZkvmVersion)},
		Resources: container.Resources{
			Ulimits:        []*container.Ulimit{{Name: "memlock", Soft: -1, Hard: -1}},
			DeviceRequests: []container.DeviceRequest{worker.GPU.DeviceRequest()},
		},
	}
	return containerCfg, hostCfg
}

// setupScript is embedded from its sidecar file so it stays editable and
// lintable as shell, with its parameters supplied as container environment.
// Embedded scripts sit next to the Go file that embeds them, one file per
// script, named after the embedding variable.
//
//go:embed setup.sh
var setupScript string

// setupSpec builds the one-off proving-key job of one worker host, given the
// same GPUs that host proves on so const-trees are built against the devices
// that will use them.
func setupSpec(cfg *Config, gpu cluster.GPU) (*container.Config, *container.HostConfig) {
	containerCfg := &container.Config{
		Image: cfg.imageRef(),
		Env: []string{
			fmt.Sprintf("KEY_URL=%s/zisk-provingkey-%s.tar.gz", setupKeyBaseURL, cfg.ZkvmVersion),
			"PROVING_KEY_DIR=" + provingKeyDir,
		},
		Cmd: []string{"bash", "-c", setupScript},
	}
	hostCfg := &container.HostConfig{
		ShmSize: 16 << 30,
		Mounts: []mount.Mount{{
			Type:   mount.TypeVolume,
			Source: provingKeyVolume(cfg.ZkvmVersion),
			Target: provingKeyDir,
		}},
		Resources: container.Resources{
			Ulimits:        []*container.Ulimit{{Name: "memlock", Soft: -1, Hard: -1}},
			DeviceRequests: []container.DeviceRequest{gpu.DeviceRequest()},
		},
	}
	return containerCfg, hostCfg
}
