package zisk

import (
	_ "embed"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/mount"
	"github.com/docker/go-connections/nat"

	"github.com/han0110/provoor/internal/cluster"
)

// The api and cluster ports are fixed so the coordinator, the workers, and
// the callers agree without configuration. The registration line is worded by
// the pinned image, so an image that rewords it updates the constant with the
// tag bump.
const (
	apiPort               = 7000
	clusterPort           = 50051
	coordinatorContainer  = "zisk-coordinator"
	workerContainer       = "zisk-worker"
	setupContainer        = "zisk-proving-key-setup"
	programSetupContainer = "zisk-program-setup"
	provingKeyDir         = "/root/.zisk/provingKey"
	cacheDir              = "/root/.zisk/cache"
	setupKeyBaseURL       = "https://storage.googleapis.com/zisk-setup"
	coordinatorConfig     = "/tmp/zisk-coordinator.toml"
	// A program setup reads the guest artifacts from these in-container paths.
	guestELFPath     = "/tmp/zisk-guest.elf"
	guestVKPath      = "/tmp/zisk-guest.vk"
	registrationLine = "Registration accepted: Registration successful"
	// computeUnitsPerGPU is what one GPU is worth to the coordinator. A worker
	// advertises this times its GPUs and the coordinator derives its readiness
	// floor the same way, so the floor tracks the GPUs deployed.
	computeUnitsPerGPU = 10
	// aggregationTimeoutSeconds replaces the 100 s the image defaults to. The
	// clock starts when the first worker finishes proving, so it bounds the
	// straggler tail, which on a full-gas block outlasts the default.
	aggregationTimeoutSeconds = 600
	// workerHealthPort is the loopback port the worker serves its health
	// verdict on under the host network. It sits next to the api port and
	// clear of 9100 through 9999, which Prometheus exporters use.
	workerHealthPort = 7001
	// coordinatorRestartPort takes restart requests for the supervisor and is
	// published beside the api port because the caller is a remote forwarder.
	coordinatorRestartPort = 7002
)

// setupScript downloads the proving key and builds its const-trees inside a
// container, with its parameters supplied as environment.
//
//go:embed script/setup.sh
var setupScript string

// programSetupScript compiles one guest into the artifact cache inside a
// container, with its parameters supplied as environment.
//
//go:embed script/program-setup.sh
var programSetupScript string

func provingKeyVolume(zkvmVersion string) string {
	return "zisk-proving-key-" + zkvmVersion
}

func provingKeyMount(zkvmVersion string) mount.Mount {
	return mount.Mount{Type: mount.TypeVolume, Source: provingKeyVolume(zkvmVersion), Target: provingKeyDir}
}

// cacheMount is the guest artifact cache the coordinator and the workers
// write. Everything in it is addressed by ELF hash, so one volume serves every
// guest and survives a down and up.
func cacheMount(zkvmVersion string) mount.Mount {
	return mount.Mount{Type: mount.TypeVolume, Source: "zisk-cache-" + zkvmVersion, Target: cacheDir}
}

// coordinatorTOML renders the coordinator config holding a job until every
// GPU of the deployment is Ready.
func coordinatorTOML(workers []Worker) string {
	gpus := 0
	for _, worker := range workers {
		gpus += worker.GPU.Len()
	}
	return fmt.Sprintf(`# Generated by provoor. Holds a job until the full cluster is Ready.
[backend]
mode = "coordinator"

[coordinator]
# Self-reference so the embedded engine re-reads this file and applies the floor.
config_file = %q
# %d compute units per gpu over %d gpus.
min_compute_units = %d
# Aggregation budget, covering the straggler tail of proof generation because
# its clock starts at the first worker to finish.
phase3_timeout_seconds = %d
`, coordinatorConfig, computeUnitsPerGPU, gpus, computeUnitsPerGPU*gpus,
		aggregationTimeoutSeconds)
}

// coordinatorSpec builds the coordinator. The supervisor runs the rest of the
// command as the coordinator and ends it on request, so the restart policy
// starts the next one.
func coordinatorSpec(cfg *Config) cluster.Container {
	api := nat.Port(fmt.Sprintf("%d/tcp", apiPort))
	clusterAPI := nat.Port(fmt.Sprintf("%d/tcp", clusterPort))
	restart := nat.Port(fmt.Sprintf("%d/tcp", coordinatorRestartPort))
	return cluster.Container{
		Name: coordinatorContainer,
		Config: &container.Config{
			Image: cfg.ImageRef(),
			Env: []string{
				"RUST_LOG=" + cluster.RustLog(cfg.Verbose),
				fmt.Sprintf("RESTART_PORT=%d", coordinatorRestartPort),
			},
			Cmd: []string{
				"zisk-supervisor",
				"zisk-coordinator",
				"--api-port", strconv.Itoa(apiPort),
				"--cluster-port", strconv.Itoa(clusterPort),
				"--config", coordinatorConfig,
			},
			ExposedPorts: nat.PortSet{api: {}, clusterAPI: {}, restart: {}},
		},
		HostConfig: &container.HostConfig{
			RestartPolicy: container.RestartPolicy{Name: container.RestartPolicyOnFailure},
			PortBindings: nat.PortMap{
				api:        {{HostPort: strconv.Itoa(apiPort)}},
				clusterAPI: {{HostPort: strconv.Itoa(clusterPort)}},
				restart:    {{HostPort: strconv.Itoa(coordinatorRestartPort)}},
			},
			LogConfig: cluster.Journald(coordinatorContainer),
			Mounts:    []mount.Mount{cacheMount(cfg.ZkvmVersion)},
		},
		Files: map[string][]byte{coordinatorConfig: []byte(coordinatorTOML(cfg.Workers))},
	}
}

// workerCoordinatorURL is the cluster URL a worker registers against. The
// worker co-located with the coordinator dials loopback.
func workerCoordinatorURL(cfg *Config, worker Worker) string {
	host := cfg.Coordinator.IP
	if worker.SSH == cfg.Coordinator.SSH {
		host = "127.0.0.1"
	}
	return fmt.Sprintf("http://%s:%d", host, clusterPort)
}

// workerArgs builds the mpirun invocation, one process spanning the host's
// GPUs with NUMA-aware rank mapping. numaNodes is the host's observed topology,
// read only when mpi_numa_ppr is unset.
func workerArgs(cfg *Config, worker Worker, name string, numaNodes int) []string {
	np := cfg.Prover.MPINp
	ppr := cfg.Prover.MPINumaPpr
	if ppr == 0 {
		ppr = max(np/max(numaNodes, 1), 1)
	}
	args := []string{
		"--report-bindings",
		"--allow-run-as-root",
		"-np", strconv.Itoa(np),
		"-map-by", fmt.Sprintf("ppr:%d:numa", ppr),
		"--bind-to", "numa",
		"--rank-by", "slot",
	}
	if cfg.Prover.MPIThreads > 0 {
		args = append(args, "-x", "RAYON_NUM_THREADS="+strconv.Itoa(cfg.Prover.MPIThreads))
	}
	args = append(args,
		"-x", "RUST_LOG="+cluster.RustLog(cfg.Verbose),
		"-x", "NO_COLOR=1",
		"-x", "ZISK_HOME=/root/.zisk",
		"-x", fmt.Sprintf("ZISK_WORKER_HEALTH_PORT=%d", workerHealthPort),
		// Witness generation walks PIL expression trees too deep for the 2 MiB
		// Rust thread default. 64 MiB matches proofman-cli's stack_size.
		"-x", "RUST_MIN_STACK=67108864",
		"zisk-worker-gpu",
		"--coordinator-url", workerCoordinatorURL(cfg, worker),
		"--worker-id", name,
		"--compute-capacity", strconv.Itoa(computeUnitsPerGPU*worker.GPU.Len()),
		"--gpu",
	)
	if cfg.Prover.CPUMops {
		args = append(args, "--cpu-mops")
	}
	args = append(args, "--proving-key", provingKeyDir)
	if cfg.Prover.MaxStreams > 0 {
		args = append(args, "--max-streams", strconv.Itoa(cfg.Prover.MaxStreams))
	}
	if cfg.Prover.NumberThreadsWitness > 0 {
		args = append(args, "--number-threads-witness", strconv.Itoa(cfg.Prover.NumberThreadsWitness))
	}
	if cfg.Prover.MaxWitnessStored > 0 {
		args = append(args, "--max-witness-stored", strconv.Itoa(cfg.Prover.MaxWitnessStored))
	}
	if cfg.Prover.MinimalMemory {
		args = append(args, "--minimal-memory")
	}
	if cfg.Verbose >= 1 {
		args = append(args, "-"+strings.Repeat("v", cfg.Verbose))
	}
	return args
}

// workerHealthProbe kills the ranks only on a body carrying the worker's
// marker with a status other than 200, so the restart policy replaces a
// worker that reports itself unrecoverable. A connection failure or an
// unmarked body leaves the worker alone, since another service can hold the
// port under the host network.
func workerHealthProbe(port int) string {
	return fmt.Sprintf(
		"code=$(curl -sS -m 4 -o /tmp/zisk-health -w %%{http_code} 127.0.0.1:%d/health) || exit 1; "+
			"grep -q '^zisk-worker ' /tmp/zisk-health || exit 1; "+
			"[ \"$code\" = 200 ] && exit 0; "+
			"pkill -KILL -x zisk-worker-gpu; exit 1",
		port,
	)
}

func workerHealthCheck() *container.HealthConfig {
	return &container.HealthConfig{
		Test:        []string{"CMD-SHELL", workerHealthProbe(workerHealthPort)},
		Interval:    30 * time.Second,
		Timeout:     10 * time.Second,
		StartPeriod: 10 * time.Minute,
		Retries:     1,
	}
}

// workerSpec builds the worker of one host. The proving key mounts writable
// because proofman regenerates a .consttree there on the first prove after a
// setup.
func workerSpec(cfg *Config, worker Worker, name string, numaNodes int) cluster.Container {
	return cluster.Container{
		Name: workerContainer,
		Config: &container.Config{
			Image:       cfg.ImageRef(),
			Entrypoint:  []string{"mpirun"},
			Cmd:         workerArgs(cfg, worker, name, numaNodes),
			Healthcheck: workerHealthCheck(),
		},
		HostConfig: &container.HostConfig{
			NetworkMode:   "host",
			RestartPolicy: container.RestartPolicy{Name: container.RestartPolicyOnFailure},
			ShmSize:       int64(cfg.Prover.ShmSizeGB) << 30,
			LogConfig:     cluster.Journald(workerContainer),
			Mounts:        []mount.Mount{provingKeyMount(cfg.ZkvmVersion), cacheMount(cfg.ZkvmVersion)},
			Resources: container.Resources{
				Ulimits:        cluster.MemlockUnlimited(),
				DeviceRequests: []container.DeviceRequest{worker.GPU.DeviceRequest()},
			},
		},
	}
}

// setupSpec builds the one-off proving-key job of one worker host on the GPUs
// that host proves on, so const-trees are built against the devices that use
// them.
func setupSpec(cfg *Config, gpu cluster.GPU) cluster.Container {
	return cluster.Container{
		Name: setupContainer,
		Config: &container.Config{
			Image: cfg.ImageRef(),
			Env: []string{
				fmt.Sprintf("KEY_URL=%s/zisk-provingkey-%s.tar.gz", setupKeyBaseURL, cfg.ZkvmVersion),
				"PROVING_KEY_DIR=" + provingKeyDir,
			},
			Cmd: []string{"bash", "-c", setupScript},
		},
		HostConfig: &container.HostConfig{
			ShmSize: 16 << 30,
			Mounts:  []mount.Mount{provingKeyMount(cfg.ZkvmVersion)},
			Resources: container.Resources{
				Ulimits:        cluster.MemlockUnlimited(),
				DeviceRequests: []container.DeviceRequest{gpu.DeviceRequest()},
			},
		},
	}
}

// programSetupSpec builds the one-off job that compiles one guest's ROM setup
// and assembly into the host's artifact cache. It runs before the cluster
// starts, since it allocates the whole device the worker would otherwise hold.
func programSetupSpec(cfg *Config, gpu cluster.GPU, elf, verifyingKey []byte) cluster.Container {
	return cluster.Container{
		Name: programSetupContainer,
		Config: &container.Config{
			Image: cfg.ImageRef(),
			Env: []string{
				"ELF_PATH=" + guestELFPath,
				"VK_PATH=" + guestVKPath,
				"PROVING_KEY_DIR=" + provingKeyDir,
				"CACHE_DIR=" + cacheDir,
				"RUST_LOG=" + cluster.RustLog(cfg.Verbose),
			},
			Cmd: []string{"bash", "-c", programSetupScript},
		},
		HostConfig: &container.HostConfig{
			ShmSize: int64(cfg.Prover.ShmSizeGB) << 30,
			Mounts:  []mount.Mount{provingKeyMount(cfg.ZkvmVersion), cacheMount(cfg.ZkvmVersion)},
			Resources: container.Resources{
				Ulimits:        cluster.MemlockUnlimited(),
				DeviceRequests: []container.DeviceRequest{gpu.DeviceRequest()},
			},
		},
		Files: map[string][]byte{guestELFPath: elf, guestVKPath: verifyingKey},
	}
}

// topologyProbeSpec builds the probe that counts the host's NUMA nodes.
func topologyProbeSpec(cfg *Config) cluster.Container {
	return cluster.Container{
		Name: workerContainer + "-probe",
		Config: &container.Config{
			Image: cfg.ImageRef(),
			Cmd:   []string{"bash", "-c", "ls -d /sys/devices/system/node/node[0-9]* 2>/dev/null | wc -l"},
		},
		HostConfig: &container.HostConfig{},
	}
}
