// Copied from https://github.com/eth-act/ere/blob/v0.18.0/crates/server/api/proto/api.proto.
//
// Regenerate api.pb.go from the repository root with protoc 3.21.12 and
// protoc-gen-go v1.36.11.
//
//   protoc --proto_path=internal/ereserver/api \
//     --go_out=internal/ereserver/api --go_opt=paths=source_relative \
//     --go_opt=Mapi.proto=github.com/han0110/provoor/internal/ereserver/api \
//     api.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputStdin    []byte                 `protobuf:"bytes,1,opt,name=input_stdin,json=inputStdin,proto3" json:"input_stdin,omitempty"`
	InputProofs   []byte                 `protobuf:"bytes,2,opt,name=input_proofs,json=inputProofs,proto3,oneof" json:"input_proofs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetInputStdin() []byte {
	if x != nil {
		return x.InputStdin
	}
	return nil
}

func (x *ExecuteRequest) GetInputProofs() []byte {
	if x != nil {
		return x.InputProofs
	}
	return nil
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ExecuteResponse_Ok
	//	*ExecuteResponse_Err
	Result        isExecuteResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetResult() isExecuteResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteResponse) GetOk() *ExecuteOk {
	if x != nil {
		if x, ok := x.Result.(*ExecuteResponse_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *ExecuteResponse) GetErr() string {
	if x != nil {
		if x, ok := x.Result.(*ExecuteResponse_Err); ok {
			return x.Err
		}
	}
	return ""
}

type isExecuteResponse_Result interface {
	isExecuteResponse_Result()
}

type ExecuteResponse_Ok struct {
	Ok *ExecuteOk `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type ExecuteResponse_Err struct {
	Err string `protobuf:"bytes,2,opt,name=err,proto3,oneof"`
}

func (*ExecuteResponse_Ok) isExecuteResponse_Result() {}

func (*ExecuteResponse_Err) isExecuteResponse_Result() {}

type ExecuteOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicValues  []byte                 `protobuf:"bytes,1,opt,name=public_values,json=publicValues,proto3" json:"public_values,omitempty"`
	DurationNanos uint64                 `protobuf:"varint,2,opt,name=duration_nanos,json=durationNanos,proto3" json:"duration_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteOk) Reset() {
	*x = ExecuteOk{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteOk) ProtoMessage() {}

func (x *ExecuteOk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteOk.ProtoReflect.Descriptor instead.
func (*ExecuteOk) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteOk) GetPublicValues() []byte {
	if x != nil {
		return x.PublicValues
	}
	return nil
}

func (x *ExecuteOk) GetDurationNanos() uint64 {
	if x != nil {
		return x.DurationNanos
	}
	return 0
}

type ExecuteEstimatedCostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputStdin    []byte                 `protobuf:"bytes,1,opt,name=input_stdin,json=inputStdin,proto3" json:"input_stdin,omitempty"`
	InputProofs   []byte                 `protobuf:"bytes,2,opt,name=input_proofs,json=inputProofs,proto3,oneof" json:"input_proofs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteEstimatedCostRequest) Reset() {
	*x = ExecuteEstimatedCostRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteEstimatedCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEstimatedCostRequest) ProtoMessage() {}

func (x *ExecuteEstimatedCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEstimatedCostRequest.ProtoReflect.Descriptor instead.
func (*ExecuteEstimatedCostRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteEstimatedCostRequest) GetInputStdin() []byte {
	if x != nil {
		return x.InputStdin
	}
	return nil
}

func (x *ExecuteEstimatedCostRequest) GetInputProofs() []byte {
	if x != nil {
		return x.InputProofs
	}
	return nil
}

type ExecuteEstimatedCostResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ExecuteEstimatedCostResponse_Ok
	//	*ExecuteEstimatedCostResponse_Err
	Result        isExecuteEstimatedCostResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteEstimatedCostResponse) Reset() {
	*x = ExecuteEstimatedCostResponse{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteEstimatedCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEstimatedCostResponse) ProtoMessage() {}

func (x *ExecuteEstimatedCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEstimatedCostResponse.ProtoReflect.Descriptor instead.
func (*ExecuteEstimatedCostResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteEstimatedCostResponse) GetResult() isExecuteEstimatedCostResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteEstimatedCostResponse) GetOk() *ExecuteEstimatedCostOk {
	if x != nil {
		if x, ok := x.Result.(*ExecuteEstimatedCostResponse_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *ExecuteEstimatedCostResponse) GetErr() string {
	if x != nil {
		if x, ok := x.Result.(*ExecuteEstimatedCostResponse_Err); ok {
			return x.Err
		}
	}
	return ""
}

type isExecuteEstimatedCostResponse_Result interface {
	isExecuteEstimatedCostResponse_Result()
}

type ExecuteEstimatedCostResponse_Ok struct {
	Ok *ExecuteEstimatedCostOk `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type ExecuteEstimatedCostResponse_Err struct {
	Err string `protobuf:"bytes,2,opt,name=err,proto3,oneof"`
}

func (*ExecuteEstimatedCostResponse_Ok) isExecuteEstimatedCostResponse_Result() {}

func (*ExecuteEstimatedCostResponse_Err) isExecuteEstimatedCostResponse_Result() {}

type ExecuteEstimatedCostOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicValues  []byte                 `protobuf:"bytes,1,opt,name=public_values,json=publicValues,proto3" json:"public_values,omitempty"`
	Cost          map[string]uint64      `protobuf:"bytes,2,rep,name=cost,proto3" json:"cost,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PeakHeapBytes *uint64                `protobuf:"varint,3,opt,name=peak_heap_bytes,json=peakHeapBytes,proto3,oneof" json:"peak_heap_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteEstimatedCostOk) Reset() {
	*x = ExecuteEstimatedCostOk{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteEstimatedCostOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEstimatedCostOk) ProtoMessage() {}

func (x *ExecuteEstimatedCostOk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEstimatedCostOk.ProtoReflect.Descriptor instead.
func (*ExecuteEstimatedCostOk) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteEstimatedCostOk) GetPublicValues() []byte {
	if x != nil {
		return x.PublicValues
	}
	return nil
}

func (x *ExecuteEstimatedCostOk) GetCost() map[string]uint64 {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *ExecuteEstimatedCostOk) GetPeakHeapBytes() uint64 {
	if x != nil && x.PeakHeapBytes != nil {
		return *x.PeakHeapBytes
	}
	return 0
}

type ProveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputStdin    []byte                 `protobuf:"bytes,1,opt,name=input_stdin,json=inputStdin,proto3" json:"input_stdin,omitempty"`
	InputProofs   []byte                 `protobuf:"bytes,2,opt,name=input_proofs,json=inputProofs,proto3,oneof" json:"input_proofs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveRequest) Reset() {
	*x = ProveRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveRequest) ProtoMessage() {}

func (x *ProveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveRequest.ProtoReflect.Descriptor instead.
func (*ProveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *ProveRequest) GetInputStdin() []byte {
	if x != nil {
		return x.InputStdin
	}
	return nil
}

func (x *ProveRequest) GetInputProofs() []byte {
	if x != nil {
		return x.InputProofs
	}
	return nil
}

type ProveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ProveResponse_Ok
	//	*ProveResponse_Err
	Result        isProveResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveResponse) Reset() {
	*x = ProveResponse{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveResponse) ProtoMessage() {}

func (x *ProveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveResponse.ProtoReflect.Descriptor instead.
func (*ProveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *ProveResponse) GetResult() isProveResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ProveResponse) GetOk() *ProveOk {
	if x != nil {
		if x, ok := x.Result.(*ProveResponse_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *ProveResponse) GetErr() string {
	if x != nil {
		if x, ok := x.Result.(*ProveResponse_Err); ok {
			return x.Err
		}
	}
	return ""
}

type isProveResponse_Result interface {
	isProveResponse_Result()
}

type ProveResponse_Ok struct {
	Ok *ProveOk `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type ProveResponse_Err struct {
	Err string `protobuf:"bytes,2,opt,name=err,proto3,oneof"`
}

func (*ProveResponse_Ok) isProveResponse_Result() {}

func (*ProveResponse_Err) isProveResponse_Result() {}

type ProveOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicValues  []byte                 `protobuf:"bytes,1,opt,name=public_values,json=publicValues,proto3" json:"public_values,omitempty"`
	Proof         []byte                 `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	DurationNanos uint64                 `protobuf:"varint,3,opt,name=duration_nanos,json=durationNanos,proto3" json:"duration_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProveOk) Reset() {
	*x = ProveOk{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProveOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProveOk) ProtoMessage() {}

func (x *ProveOk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProveOk.ProtoReflect.Descriptor instead.
func (*ProveOk) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *ProveOk) GetPublicValues() []byte {
	if x != nil {
		return x.PublicValues
	}
	return nil
}

func (x *ProveOk) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *ProveOk) GetDurationNanos() uint64 {
	if x != nil {
		return x.DurationNanos
	}
	return 0
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         []byte                 `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyRequest) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type VerifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*VerifyResponse_Ok
	//	*VerifyResponse_Err
	Result        isVerifyResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyResponse) GetResult() isVerifyResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *VerifyResponse) GetOk() *VerifyOk {
	if x != nil {
		if x, ok := x.Result.(*VerifyResponse_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *VerifyResponse) GetErr() string {
	if x != nil {
		if x, ok := x.Result.(*VerifyResponse_Err); ok {
			return x.Err
		}
	}
	return ""
}

type isVerifyResponse_Result interface {
	isVerifyResponse_Result()
}

type VerifyResponse_Ok struct {
	Ok *VerifyOk `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type VerifyResponse_Err struct {
	Err string `protobuf:"bytes,2,opt,name=err,proto3,oneof"`
}

func (*VerifyResponse_Ok) isVerifyResponse_Result() {}

func (*VerifyResponse_Err) isVerifyResponse_Result() {}

type VerifyOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicValues  []byte                 `protobuf:"bytes,1,opt,name=public_values,json=publicValues,proto3" json:"public_values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOk) Reset() {
	*x = VerifyOk{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOk) ProtoMessage() {}

func (x *VerifyOk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOk.ProtoReflect.Descriptor instead.
func (*VerifyOk) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyOk) GetPublicValues() []byte {
	if x != nil {
		return x.PublicValues
	}
	return nil
}

type ProgramVkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramVkRequest) Reset() {
	*x = ProgramVkRequest{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramVkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramVkRequest) ProtoMessage() {}

func (x *ProgramVkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramVkRequest.ProtoReflect.Descriptor instead.
func (*ProgramVkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

type ProgramVkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ProgramVkResponse_Ok
	//	*ProgramVkResponse_Err
	Result        isProgramVkResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramVkResponse) Reset() {
	*x = ProgramVkResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramVkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramVkResponse) ProtoMessage() {}

func (x *ProgramVkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramVkResponse.ProtoReflect.Descriptor instead.
func (*ProgramVkResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *ProgramVkResponse) GetResult() isProgramVkResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ProgramVkResponse) GetOk() *ProgramVkOk {
	if x != nil {
		if x, ok := x.Result.(*ProgramVkResponse_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *ProgramVkResponse) GetErr() string {
	if x != nil {
		if x, ok := x.Result.(*ProgramVkResponse_Err); ok {
			return x.Err
		}
	}
	return ""
}

type isProgramVkResponse_Result interface {
	isProgramVkResponse_Result()
}

type ProgramVkResponse_Ok struct {
	Ok *ProgramVkOk `protobuf:"bytes,1,opt,name=ok,proto3,oneof"`
}

type ProgramVkResponse_Err struct {
	Err string `protobuf:"bytes,2,opt,name=err,proto3,oneof"`
}

func (*ProgramVkResponse_Ok) isProgramVkResponse_Result() {}

func (*ProgramVkResponse_Err) isProgramVkResponse_Result() {}

type ProgramVkOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramVk     []byte                 `protobuf:"bytes,1,opt,name=program_vk,json=programVk,proto3" json:"program_vk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramVkOk) Reset() {
	*x = ProgramVkOk{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramVkOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramVkOk) ProtoMessage() {}

func (x *ProgramVkOk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramVkOk.ProtoReflect.Descriptor instead.
func (*ProgramVkOk) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *ProgramVkOk) GetProgramVk() []byte {
	if x != nil {
		return x.ProgramVk
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\"j\n" +
	"\x0eExecuteRequest\x12\x1f\n" +
	"\vinput_stdin\x18\x01 \x01(\fR\n" +
	"inputStdin\x12&\n" +
	"\finput_proofs\x18\x02 \x01(\fH\x00R\vinputProofs\x88\x01\x01B\x0f\n" +
	"\r_input_proofs\"Q\n" +
	"\x0fExecuteResponse\x12 \n" +
	"\x02ok\x18\x01 \x01(\v2\x0e.api.ExecuteOkH\x00R\x02ok\x12\x12\n" +
	"\x03err\x18\x02 \x01(\tH\x00R\x03errB\b\n" +
	"\x06result\"W\n" +
	"\tExecuteOk\x12#\n" +
	"\rpublic_values\x18\x01 \x01(\fR\fpublicValues\x12%\n" +
	"\x0eduration_nanos\x18\x02 \x01(\x04R\rdurationNanos\"w\n" +
	"\x1bExecuteEstimatedCostRequest\x12\x1f\n" +
	"\vinput_stdin\x18\x01 \x01(\fR\n" +
	"inputStdin\x12&\n" +
	"\finput_proofs\x18\x02 \x01(\fH\x00R\vinputProofs\x88\x01\x01B\x0f\n" +
	"\r_input_proofs\"k\n" +
	"\x1cExecuteEstimatedCostResponse\x12-\n" +
	"\x02ok\x18\x01 \x01(\v2\x1b.api.ExecuteEstimatedCostOkH\x00R\x02ok\x12\x12\n" +
	"\x03err\x18\x02 \x01(\tH\x00R\x03errB\b\n" +
	"\x06result\"\xf2\x01\n" +
	"\x16ExecuteEstimatedCostOk\x12#\n" +
	"\rpublic_values\x18\x01 \x01(\fR\fpublicValues\x129\n" +
	"\x04cost\x18\x02 \x03(\v2%.api.ExecuteEstimatedCostOk.CostEntryR\x04cost\x12+\n" +
	"\x0fpeak_heap_bytes\x18\x03 \x01(\x04H\x00R\rpeakHeapBytes\x88\x01\x01\x1a7\n" +
	"\tCostEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01B\x12\n" +
	"\x10_peak_heap_bytes\"h\n" +
	"\fProveRequest\x12\x1f\n" +
	"\vinput_stdin\x18\x01 \x01(\fR\n" +
	"inputStdin\x12&\n" +
	"\finput_proofs\x18\x02 \x01(\fH\x00R\vinputProofs\x88\x01\x01B\x0f\n" +
	"\r_input_proofs\"M\n" +
	"\rProveResponse\x12\x1e\n" +
	"\x02ok\x18\x01 \x01(\v2\f.api.ProveOkH\x00R\x02ok\x12\x12\n" +
	"\x03err\x18\x02 \x01(\tH\x00R\x03errB\b\n" +
	"\x06result\"k\n" +
	"\aProveOk\x12#\n" +
	"\rpublic_values\x18\x01 \x01(\fR\fpublicValues\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12%\n" +
	"\x0eduration_nanos\x18\x03 \x01(\x04R\rdurationNanos\"%\n" +
	"\rVerifyRequest\x12\x14\n" +
	"\x05proof\x18\x01 \x01(\fR\x05proof\"O\n" +
	"\x0eVerifyResponse\x12\x1f\n" +
	"\x02ok\x18\x01 \x01(\v2\r.api.VerifyOkH\x00R\x02ok\x12\x12\n" +
	"\x03err\x18\x02 \x01(\tH\x00R\x03errB\b\n" +
	"\x06result\"/\n" +
	"\bVerifyOk\x12#\n" +
	"\rpublic_values\x18\x01 \x01(\fR\fpublicValues\"\x12\n" +
	"\x10ProgramVkRequest\"U\n" +
	"\x11ProgramVkResponse\x12\"\n" +
	"\x02ok\x18\x01 \x01(\v2\x10.api.ProgramVkOkH\x00R\x02ok\x12\x12\n" +
	"\x03err\x18\x02 \x01(\tH\x00R\x03errB\b\n" +
	"\x06result\",\n" +
	"\vProgramVkOk\x12\x1d\n" +
	"\n" +
	"program_vk\x18\x01 \x01(\fR\tprogramVk2\xc9\x02\n" +
	"\vZkvmService\x126\n" +
	"\aExecute\x12\x13.api.ExecuteRequest\x1a\x14.api.ExecuteResponse\"\x00\x12]\n" +
	"\x14ExecuteEstimatedCost\x12 .api.ExecuteEstimatedCostRequest\x1a!.api.ExecuteEstimatedCostResponse\"\x00\x120\n" +
	"\x05Prove\x12\x11.api.ProveRequest\x1a\x12.api.ProveResponse\"\x00\x123\n" +
	"\x06Verify\x12\x12.api.VerifyRequest\x1a\x13.api.VerifyResponse\"\x00\x12<\n" +
	"\tProgramVk\x12\x15.api.ProgramVkRequest\x1a\x16.api.ProgramVkResponse\"\x00b\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_goTypes = []any{
	(*ExecuteRequest)(nil),               // 0: api.ExecuteRequest
	(*ExecuteResponse)(nil),              // 1: api.ExecuteResponse
	(*ExecuteOk)(nil),                    // 2: api.ExecuteOk
	(*ExecuteEstimatedCostRequest)(nil),  // 3: api.ExecuteEstimatedCostRequest
	(*ExecuteEstimatedCostResponse)(nil), // 4: api.ExecuteEstimatedCostResponse
	(*ExecuteEstimatedCostOk)(nil),       // 5: api.ExecuteEstimatedCostOk
	(*ProveRequest)(nil),                 // 6: api.ProveRequest
	(*ProveResponse)(nil),                // 7: api.ProveResponse
	(*ProveOk)(nil),                      // 8: api.ProveOk
	(*VerifyRequest)(nil),                // 9: api.VerifyRequest
	(*VerifyResponse)(nil),               // 10: api.VerifyResponse
	(*VerifyOk)(nil),                     // 11: api.VerifyOk
	(*ProgramVkRequest)(nil),             // 12: api.ProgramVkRequest
	(*ProgramVkResponse)(nil),            // 13: api.ProgramVkResponse
	(*ProgramVkOk)(nil),                  // 14: api.ProgramVkOk
	nil,                                  // 15: api.ExecuteEstimatedCostOk.CostEntry
}
var file_api_proto_depIdxs = []int32{
	2,  // 0: api.ExecuteResponse.ok:type_name -> api.ExecuteOk
	5,  // 1: api.ExecuteEstimatedCostResponse.ok:type_name -> api.ExecuteEstimatedCostOk
	15, // 2: api.ExecuteEstimatedCostOk.cost:type_name -> api.ExecuteEstimatedCostOk.CostEntry
	8,  // 3: api.ProveResponse.ok:type_name -> api.ProveOk
	11, // 4: api.VerifyResponse.ok:type_name -> api.VerifyOk
	14, // 5: api.ProgramVkResponse.ok:type_name -> api.ProgramVkOk
	0,  // 6: api.ZkvmService.Execute:input_type -> api.ExecuteRequest
	3,  // 7: api.ZkvmService.ExecuteEstimatedCost:input_type -> api.ExecuteEstimatedCostRequest
	6,  // 8: api.ZkvmService.Prove:input_type -> api.ProveRequest
	9,  // 9: api.ZkvmService.Verify:input_type -> api.VerifyRequest
	12, // 10: api.ZkvmService.ProgramVk:input_type -> api.ProgramVkRequest
	1,  // 11: api.ZkvmService.Execute:output_type -> api.ExecuteResponse
	4,  // 12: api.ZkvmService.ExecuteEstimatedCost:output_type -> api.ExecuteEstimatedCostResponse
	7,  // 13: api.ZkvmService.Prove:output_type -> api.ProveResponse
	10, // 14: api.ZkvmService.Verify:output_type -> api.VerifyResponse
	13, // 15: api.ZkvmService.ProgramVk:output_type -> api.ProgramVkResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_msgTypes[1].OneofWrappers = []any{
		(*ExecuteResponse_Ok)(nil),
		(*ExecuteResponse_Err)(nil),
	}
	file_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_msgTypes[4].OneofWrappers = []any{
		(*ExecuteEstimatedCostResponse_Ok)(nil),
		(*ExecuteEstimatedCostResponse_Err)(nil),
	}
	file_api_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_proto_msgTypes[7].OneofWrappers = []any{
		(*ProveResponse_Ok)(nil),
		(*ProveResponse_Err)(nil),
	}
	file_api_proto_msgTypes[10].OneofWrappers = []any{
		(*VerifyResponse_Ok)(nil),
		(*VerifyResponse_Err)(nil),
	}
	file_api_proto_msgTypes[13].OneofWrappers = []any{
		(*ProgramVkResponse_Ok)(nil),
		(*ProgramVkResponse_Err)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
