// Copied from https://github.com/0xPolygonHermez/zisk/blob/v1.2.0-alpha/distributed/crates/coordinator-api/proto/zisk_coordinator_api.proto.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: zisk_coordinator_api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZiskCoordinatorApi_RegisterGuestProgram_FullMethodName       = "/zisk.coordinator.v1.ZiskCoordinatorApi/RegisterGuestProgram"
	ZiskCoordinatorApi_RegisterAggregationProgram_FullMethodName = "/zisk.coordinator.v1.ZiskCoordinatorApi/RegisterAggregationProgram"
	ZiskCoordinatorApi_JobRequest_FullMethodName                 = "/zisk.coordinator.v1.ZiskCoordinatorApi/JobRequest"
	ZiskCoordinatorApi_WaitJobResult_FullMethodName              = "/zisk.coordinator.v1.ZiskCoordinatorApi/WaitJobResult"
	ZiskCoordinatorApi_WatchJob_FullMethodName                   = "/zisk.coordinator.v1.ZiskCoordinatorApi/WatchJob"
	ZiskCoordinatorApi_PushJobInput_FullMethodName               = "/zisk.coordinator.v1.ZiskCoordinatorApi/PushJobInput"
	ZiskCoordinatorApi_PushJobHintsInput_FullMethodName          = "/zisk.coordinator.v1.ZiskCoordinatorApi/PushJobHintsInput"
	ZiskCoordinatorApi_CancelJob_FullMethodName                  = "/zisk.coordinator.v1.ZiskCoordinatorApi/CancelJob"
)

// ZiskCoordinatorApiClient is the client API for ZiskCoordinatorApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZiskCoordinatorApiClient interface {
	// Register a new guest program. Idempotent: the same ELF always returns
	// the same hash_id.
	RegisterGuestProgram(ctx context.Context, in *RegisterGuestProgramRequest, opts ...grpc.CallOption) (*RegisterGuestProgramResponse, error)
	// Register a recurser spec. Idempotent: the same spec always
	// returns the same recurser_id (a content hash of the inputs).
	RegisterAggregationProgram(ctx context.Context, in *RegisterAggregationProgramRequest, opts ...grpc.CallOption) (*RegisterAggregationProgramResponse, error)
	// Submit a new job (setup, prove, wrap, execute, setup_aggregation_program, aggregate_proofs).
	JobRequest(ctx context.Context, in *JobRequestMessage, opts ...grpc.CallOption) (*JobResponse, error)
	// Long-poll: block until the job reaches a terminal state or the server-side
	// timeout elapses, then return the current status. Loop on this to poll to
	// completion without application-level sleep.
	WaitJobResult(ctx context.Context, in *WaitJobResultRequest, opts ...grpc.CallOption) (*WaitJobResultResponse, error)
	// Subscribe to live state-transition events for a job. The stream closes
	// after the terminal event. Safe to call after the job has already finished.
	WatchJob(ctx context.Context, in *WatchJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error)
	// Stream additional input chunks to a running job.
	// Close the stream to signal end-of-input (EOF).
	PushJobInput(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushJobInputRequest, emptypb.Empty], error)
	// Stream additional hints chunks to a running job.
	// Close the stream to signal end-of-hints (EOF).
	PushJobHintsInput(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushJobHintsInputRequest, emptypb.Empty], error)
	// Cancel a running or queued job. Blocks until the job reaches a terminal
	// state (Cancelled or another terminal if it completed first).
	// Idempotent: returns cancelled=false if the job is already in a terminal state.
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
}

type ziskCoordinatorApiClient struct {
	cc grpc.ClientConnInterface
}

func NewZiskCoordinatorApiClient(cc grpc.ClientConnInterface) ZiskCoordinatorApiClient {
	return &ziskCoordinatorApiClient{cc}
}

func (c *ziskCoordinatorApiClient) RegisterGuestProgram(ctx context.Context, in *RegisterGuestProgramRequest, opts ...grpc.CallOption) (*RegisterGuestProgramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterGuestProgramResponse)
	err := c.cc.Invoke(ctx, ZiskCoordinatorApi_RegisterGuestProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ziskCoordinatorApiClient) RegisterAggregationProgram(ctx context.Context, in *RegisterAggregationProgramRequest, opts ...grpc.CallOption) (*RegisterAggregationProgramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAggregationProgramResponse)
	err := c.cc.Invoke(ctx, ZiskCoordinatorApi_RegisterAggregationProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ziskCoordinatorApiClient) JobRequest(ctx context.Context, in *JobRequestMessage, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, ZiskCoordinatorApi_JobRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ziskCoordinatorApiClient) WaitJobResult(ctx context.Context, in *WaitJobResultRequest, opts ...grpc.CallOption) (*WaitJobResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitJobResultResponse)
	err := c.cc.Invoke(ctx, ZiskCoordinatorApi_WaitJobResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ziskCoordinatorApiClient) WatchJob(ctx context.Context, in *WatchJobRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZiskCoordinatorApi_ServiceDesc.Streams[0], ZiskCoordinatorApi_WatchJob_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchJobRequest, JobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZiskCoordinatorApi_WatchJobClient = grpc.ServerStreamingClient[JobEvent]

func (c *ziskCoordinatorApiClient) PushJobInput(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushJobInputRequest, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZiskCoordinatorApi_ServiceDesc.Streams[1], ZiskCoordinatorApi_PushJobInput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushJobInputRequest, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZiskCoordinatorApi_PushJobInputClient = grpc.ClientStreamingClient[PushJobInputRequest, emptypb.Empty]

func (c *ziskCoordinatorApiClient) PushJobHintsInput(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PushJobHintsInputRequest, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZiskCoordinatorApi_ServiceDesc.Streams[2], ZiskCoordinatorApi_PushJobHintsInput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushJobHintsInputRequest, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZiskCoordinatorApi_PushJobHintsInputClient = grpc.ClientStreamingClient[PushJobHintsInputRequest, emptypb.Empty]

func (c *ziskCoordinatorApiClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, ZiskCoordinatorApi_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZiskCoordinatorApiServer is the server API for ZiskCoordinatorApi service.
// All implementations must embed UnimplementedZiskCoordinatorApiServer
// for forward compatibility.
type ZiskCoordinatorApiServer interface {
	// Register a new guest program. Idempotent: the same ELF always returns
	// the same hash_id.
	RegisterGuestProgram(context.Context, *RegisterGuestProgramRequest) (*RegisterGuestProgramResponse, error)
	// Register a recurser spec. Idempotent: the same spec always
	// returns the same recurser_id (a content hash of the inputs).
	RegisterAggregationProgram(context.Context, *RegisterAggregationProgramRequest) (*RegisterAggregationProgramResponse, error)
	// Submit a new job (setup, prove, wrap, execute, setup_aggregation_program, aggregate_proofs).
	JobRequest(context.Context, *JobRequestMessage) (*JobResponse, error)
	// Long-poll: block until the job reaches a terminal state or the server-side
	// timeout elapses, then return the current status. Loop on this to poll to
	// completion without application-level sleep.
	WaitJobResult(context.Context, *WaitJobResultRequest) (*WaitJobResultResponse, error)
	// Subscribe to live state-transition events for a job. The stream closes
	// after the terminal event. Safe to call after the job has already finished.
	WatchJob(*WatchJobRequest, grpc.ServerStreamingServer[JobEvent]) error
	// Stream additional input chunks to a running job.
	// Close the stream to signal end-of-input (EOF).
	PushJobInput(grpc.ClientStreamingServer[PushJobInputRequest, emptypb.Empty]) error
	// Stream additional hints chunks to a running job.
	// Close the stream to signal end-of-hints (EOF).
	PushJobHintsInput(grpc.ClientStreamingServer[PushJobHintsInputRequest, emptypb.Empty]) error
	// Cancel a running or queued job. Blocks until the job reaches a terminal
	// state (Cancelled or another terminal if it completed first).
	// Idempotent: returns cancelled=false if the job is already in a terminal state.
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	mustEmbedUnimplementedZiskCoordinatorApiServer()
}

// UnimplementedZiskCoordinatorApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZiskCoordinatorApiServer struct{}

func (UnimplementedZiskCoordinatorApiServer) RegisterGuestProgram(context.Context, *RegisterGuestProgramRequest) (*RegisterGuestProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterGuestProgram not implemented")
}
func (UnimplementedZiskCoordinatorApiServer) RegisterAggregationProgram(context.Context, *RegisterAggregationProgramRequest) (*RegisterAggregationProgramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAggregationProgram not implemented")
}
func (UnimplementedZiskCoordinatorApiServer) JobRequest(context.Context, *JobRequestMessage) (*JobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JobRequest not implemented")
}
func (UnimplementedZiskCoordinatorApiServer) WaitJobResult(context.Context, *WaitJobResultRequest) (*WaitJobResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitJobResult not implemented")
}
func (UnimplementedZiskCoordinatorApiServer) WatchJob(*WatchJobRequest, grpc.ServerStreamingServer[JobEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchJob not implemented")
}
func (UnimplementedZiskCoordinatorApiServer) PushJobInput(grpc.ClientStreamingServer[PushJobInputRequest, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method PushJobInput not implemented")
}
func (UnimplementedZiskCoordinatorApiServer) PushJobHintsInput(grpc.ClientStreamingServer[PushJobHintsInputRequest, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method PushJobHintsInput not implemented")
}
func (UnimplementedZiskCoordinatorApiServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedZiskCoordinatorApiServer) mustEmbedUnimplementedZiskCoordinatorApiServer() {}
func (UnimplementedZiskCoordinatorApiServer) testEmbeddedByValue()                            {}

// UnsafeZiskCoordinatorApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZiskCoordinatorApiServer will
// result in compilation errors.
type UnsafeZiskCoordinatorApiServer interface {
	mustEmbedUnimplementedZiskCoordinatorApiServer()
}

func RegisterZiskCoordinatorApiServer(s grpc.ServiceRegistrar, srv ZiskCoordinatorApiServer) {
	// If the following call pancis, it indicates UnimplementedZiskCoordinatorApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZiskCoordinatorApi_ServiceDesc, srv)
}

func _ZiskCoordinatorApi_RegisterGuestProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterGuestProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZiskCoordinatorApiServer).RegisterGuestProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZiskCoordinatorApi_RegisterGuestProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZiskCoordinatorApiServer).RegisterGuestProgram(ctx, req.(*RegisterGuestProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZiskCoordinatorApi_RegisterAggregationProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAggregationProgramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZiskCoordinatorApiServer).RegisterAggregationProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZiskCoordinatorApi_RegisterAggregationProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZiskCoordinatorApiServer).RegisterAggregationProgram(ctx, req.(*RegisterAggregationProgramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZiskCoordinatorApi_JobRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZiskCoordinatorApiServer).JobRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZiskCoordinatorApi_JobRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZiskCoordinatorApiServer).JobRequest(ctx, req.(*JobRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZiskCoordinatorApi_WaitJobResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitJobResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZiskCoordinatorApiServer).WaitJobResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZiskCoordinatorApi_WaitJobResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZiskCoordinatorApiServer).WaitJobResult(ctx, req.(*WaitJobResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZiskCoordinatorApi_WatchJob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchJobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZiskCoordinatorApiServer).WatchJob(m, &grpc.GenericServerStream[WatchJobRequest, JobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZiskCoordinatorApi_WatchJobServer = grpc.ServerStreamingServer[JobEvent]

func _ZiskCoordinatorApi_PushJobInput_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZiskCoordinatorApiServer).PushJobInput(&grpc.GenericServerStream[PushJobInputRequest, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZiskCoordinatorApi_PushJobInputServer = grpc.ClientStreamingServer[PushJobInputRequest, emptypb.Empty]

func _ZiskCoordinatorApi_PushJobHintsInput_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ZiskCoordinatorApiServer).PushJobHintsInput(&grpc.GenericServerStream[PushJobHintsInputRequest, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZiskCoordinatorApi_PushJobHintsInputServer = grpc.ClientStreamingServer[PushJobHintsInputRequest, emptypb.Empty]

func _ZiskCoordinatorApi_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZiskCoordinatorApiServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZiskCoordinatorApi_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZiskCoordinatorApiServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZiskCoordinatorApi_ServiceDesc is the grpc.ServiceDesc for ZiskCoordinatorApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZiskCoordinatorApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zisk.coordinator.v1.ZiskCoordinatorApi",
	HandlerType: (*ZiskCoordinatorApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterGuestProgram",
			Handler:    _ZiskCoordinatorApi_RegisterGuestProgram_Handler,
		},
		{
			MethodName: "RegisterAggregationProgram",
			Handler:    _ZiskCoordinatorApi_RegisterAggregationProgram_Handler,
		},
		{
			MethodName: "JobRequest",
			Handler:    _ZiskCoordinatorApi_JobRequest_Handler,
		},
		{
			MethodName: "WaitJobResult",
			Handler:    _ZiskCoordinatorApi_WaitJobResult_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _ZiskCoordinatorApi_CancelJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchJob",
			Handler:       _ZiskCoordinatorApi_WatchJob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PushJobInput",
			Handler:       _ZiskCoordinatorApi_PushJobInput_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "PushJobHintsInput",
			Handler:       _ZiskCoordinatorApi_PushJobHintsInput_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "zisk_coordinator_api.proto",
}
